language: php
php:
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

before_script:
 - mysql -e 'create database drupal;'
 - pyrus channel-discover pear.drush.org
 - pyrus install drush/drush
 - phpenv rehash
 - mkdir private
 - mkdir tmp
 - drush make drushmake/drupalmatic.make drupal
 - cp -r drushmake/drupalmatic drupal/profiles
 - cd drupal
 - php -d sendmail_path=/dev/null `which drush` si drupalmatic --db-url=mysql://root:@localhost/drupal --yes
 - drush en --yes simpletest
 - drush cc all
 - drush runserver --server=builtin 8080 &
 - sleep 4
 - drush vset --yes simpletest_verbose FALSE
 - cd ..
 - composer --no-progress install

script:
# Start with behavioral tests.
  - bin/behat -c travis.behat.yml
# Now for Drupal SimpleTest.
#  - cd drupal
# Set up to run the PHP test group under SimpleTest, since it's quick.
# Change this line to include all the test groups you want to run.
#  drush test-run SomeGroup,AnotherGroup --uri=http://localhost:8080/
#  - sudo -u apache drush test-run PHP --uri=http://localhost:8080/
